# Generated by Django 5.1.3 on 2024-12-18 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='lifetime',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
